export const ERROR_MESSAGES = {
  INVALID_JSON_FILE_ERROR: "Your json file is invalid, please check it!\n",
  INVALID_FILE_FORMAT: "Your input file is invalid, please check if it json or yaml!\n",
  FETCH_CLIENT_FAILED_ERROR: "Fetch client failed! Please check your network or ts-codegen.config.ts file.\n",
  NO_CLIENTS_OR_DATA: "You should provide at least one client or data file!\n",
};
export const LOG_MESSAGE = {
  GENERATING: "☄️ Generating...",
  SUCCESSFUL: "🥳 All request data generated successful!!!\n",
  LOCAL_SUCCESSFUL: (fileIndex: number) => `✅  Request data generated successful from file${fileIndex + 1}!!!\n`,
  READING_FROM_LOCAL: (fileIndex: number) => `👓 Reading swagger schema from local file${fileIndex + 1}...`,
  GETTING_FROM_REMOTE: (index: number) => `🛜 Getting swagger schema from client ${index + 1}...`,
  REMOTE_SUCCESSFUL: (index: number) => `✅  Request data generated successful from client${index + 1}!!!\n`,
  MISSING_OPERATION_ID:
    "⚠️ Some of your request does not have an operation id, generated request method will not has an uniq name!",
};
export const HTTP_METHODS = ["get", "post", "put", "delete", "patch", "options", "head"];
export const SLASH = "/";
export const FILE_TIP = `\n/* 
    *  this file is generated by @openapi-integration/swr-request-generator.
    *  please do not modify it manually.
    */\n
  `;
export const getSplittingMessage = (fileIndex: number) => `// * No${fileIndex + 1} Request File Content *\n`;
export const ENUM_SUFFIX = `#EnumTypeSuffix`;
